// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/AlecSmith96/dating-api/internal/usecases (interfaces: JwtProcessor)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=../../mocks/jwtProcessor.go . JwtProcessor
//
// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockJwtProcessor is a mock of JwtProcessor interface.
type MockJwtProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockJwtProcessorMockRecorder
}

// MockJwtProcessorMockRecorder is the mock recorder for MockJwtProcessor.
type MockJwtProcessorMockRecorder struct {
	mock *MockJwtProcessor
}

// NewMockJwtProcessor creates a new mock instance.
func NewMockJwtProcessor(ctrl *gomock.Controller) *MockJwtProcessor {
	mock := &MockJwtProcessor{ctrl: ctrl}
	mock.recorder = &MockJwtProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtProcessor) EXPECT() *MockJwtProcessorMockRecorder {
	return m.recorder
}

// ValidateJwtForUser mocks base method.
func (m *MockJwtProcessor) ValidateJwtForUser(arg0 string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateJwtForUser", arg0)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateJwtForUser indicates an expected call of ValidateJwtForUser.
func (mr *MockJwtProcessorMockRecorder) ValidateJwtForUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateJwtForUser", reflect.TypeOf((*MockJwtProcessor)(nil).ValidateJwtForUser), arg0)
}
